name: build-test-vite-plugin-lxr

on:
  push:
    paths:
      - packages/core/**
      - packages/vite-plugin-lxr/**
      - .github/workflows/build-vite-plugin-lxr.yml

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test-and-build:
    name: Lint & Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:vite-plugin-lxr

      - name: Build
        run: npm run build:vite-plugin-lxr
